AllCops:
  TargetRubyVersion: 2.5
  NewCops: disable
  SuggestExtensions: false

Style/Alias:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Layout/LineLength:
  Max: 120

# require "pp" in specs is flagged in Ruby 2.6 but not in other ones
# and doing a point disable gets a "unused lint" warning, so this is easier
# to disable here
Lint/RedundantRequireStatement:
    Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
